--
-- Table structure for table `make`
--

CREATE TABLE IF NOT EXISTS `vehicle_manufacturers` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `code` varchar(55) NOT NULL DEFAULT '',
  `name` varchar(55) NOT NULL DEFAULT '',
  `image` varchar(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=72 ;

--
-- Dumping data for table `make`
--

INSERT INTO `vehicle_manufacturers` (`id`, `code`, `name`, `image`) VALUES
(1, 'ACURA', 'Acura', NULL),
(2, 'ALFA', 'Alfa Romeo', NULL),
(3, 'AMC', 'AMC', NULL),
(4, 'ASTON', 'Aston Martin', NULL),
(5, 'AUDI', 'Audi', NULL),
(6, 'AVANTI', 'Avanti', NULL),
(7, 'BENTL', 'Bentley', NULL),
(8, 'BMW', 'BMW', NULL),
(9, 'BUICK', 'Buick', NULL),
(10, 'CAD', 'Cadillac', NULL),
(11, 'CHEV', 'Chevrolet', NULL),
(12, 'CHRY', 'Chrysler', NULL),
(13, 'DAEW', 'Daewoo', NULL),
(14, 'DAIHAT', 'Daihatsu', NULL),
(15, 'DATSUN', 'Datsun', NULL),
(16, 'DELOREAN', 'DeLorean', NULL),
(17, 'DODGE', 'Dodge', NULL),
(18, 'EAGLE', 'Eagle', NULL),
(19, 'FER', 'Ferrari', NULL),
(20, 'FIAT', 'FIAT', NULL),
(21, 'FISK', 'Fisker', NULL),
(22, 'FORD', 'Ford', NULL),
(23, 'FREIGHT', 'Freightliner', NULL),
(24, 'GEO', 'Geo', NULL),
(25, 'GMC', 'GMC', NULL),
(26, 'HONDA', 'Honda', NULL),
(27, 'AMGEN', 'HUMMER', NULL),
(28, 'HYUND', 'Hyundai', NULL),
(29, 'INFIN', 'Infiniti', NULL),
(30, 'ISU', 'Isuzu', NULL),
(31, 'JAG', 'Jaguar', NULL),
(32, 'JEEP', 'Jeep', NULL),
(33, 'KIA', 'Kia', NULL),
(34, 'LAM', 'Lamborghini', NULL),
(35, 'LAN', 'Lancia', NULL),
(36, 'ROV', 'Land Rover', NULL),
(37, 'LEXUS', 'Lexus', NULL),
(38, 'LINC', 'Lincoln', NULL),
(39, 'LOTUS', 'Lotus', NULL),
(40, 'MAS', 'Maserati', NULL),
(41, 'MAYBACH', 'Maybach', NULL),
(42, 'MAZDA', 'Mazda', NULL),
(43, 'MCLAREN', 'McLaren', NULL),
(44, 'MB', 'Mercedes-Benz', NULL),
(45, 'MERC', 'Mercury', NULL),
(46, 'MERKUR', 'Merkur', NULL),
(47, 'MINI', 'MINI', NULL),
(48, 'MIT', 'Mitsubishi', NULL),
(49, 'NISSAN', 'Nissan', NULL),
(50, 'OLDS', 'Oldsmobile', NULL),
(51, 'PEUG', 'Peugeot', NULL),
(52, 'PLYM', 'Plymouth', NULL),
(53, 'PONT', 'Pontiac', NULL),
(54, 'POR', 'Porsche', NULL),
(55, 'RAM', 'RAM', NULL),
(56, 'REN', 'Renault', NULL),
(57, 'RR', 'Rolls-Royce', NULL),
(58, 'SAAB', 'Saab', NULL),
(59, 'SATURN', 'Saturn', NULL),
(60, 'SCION', 'Scion', NULL),
(61, 'SMART', 'smart', NULL),
(62, 'SRT', 'SRT', NULL),
(63, 'STERL', 'Sterling', NULL),
(64, 'SUB', 'Subaru', NULL),
(65, 'SUZUKI', 'Suzuki', NULL),
(66, 'TESLA', 'Tesla', NULL),
(67, 'TOYOTA', 'Toyota', NULL),
(68, 'TRI', 'Triumph', NULL),
(69, 'VOLKS', 'Volkswagen', NULL),
(70, 'VOLVO', 'Volvo', NULL),
(71, 'YUGO', 'Yugo', NULL);

-- --------------------------------------------------------
