on:

  push:

    branches:

      - main

name: 🚀 Deploy to staging repo

jobs:

  web-deploy:

    name: 🎉 Deploy

    runs-on: ubuntu-latest

    steps:

    - name: 🚚 Get latest code

      uses: actions/checkout@v2


    - name: Use Node.js 14

      uses: actions/setup-node@v2

      with:

        node-version: '14'



    - name: 🔨 Migrations and clearing caches

      run: |

        #php artisan clean


    - name: 📂 Sync files

      uses: SamKirkland/FTP-Deploy-Action@4.2.0

      with:

        server: ftp.cityfare.ng

        username: ${{ secrets.ftp_username_codebase }}
        password: ${{ secrets.ftp_password_codebase }}
        protocol: sftp
        port: 22

        exclude: |

          **/.git*

          **/.git*/**

          **/node_modules/**

          **/vendor/**

